name: mobile_app_analytics
version: 1.0.0
config-version: 2

profile: mobile_app_analytics  # change to your dbt profile name

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  mobile_app_analytics:
    +materialized: view

    staging:
      +materialized: view

    intermediate:
      +materialized: table

    marts:
      +materialized: table

    dimensions:
      +materialized: table
