[workspace]
resolver = "2"
members = [
  "src/runtime",
  "src/core",
  "src/suites/react-suites",
  "src/modules/storage",
  "src/modules/provider-vector-lance",
  "src/suites/react-suites/src/data_engineer/modules/provider-postgres",
  "src/suites/react-suites/src/data_engineer/modules/provider-bigquery",
  "src/suites/react-suites/src/data_engineer/modules/provider-athena",
  "src/suites/react-suites/src/data_engineer/modules/provider-dbt",
]
