[workspace]
resolver = "2"
members = [
  "src/runtime",
  "src/core",
  "src/view",
  "src/suites/data_engineer",
  "src/suites/kb",
  "src/modules/adaptors/storage-s3",
  "src/modules/adaptors/storage-local",
  "src/modules/adaptors/storage-memory",
  "src/modules/providers/vector-lance",
  "src/suites/data_engineer/src/modules/provider-postgres",
  "src/suites/data_engineer/src/modules/provider-bigquery",
  "src/suites/data_engineer/src/modules/provider-athena",
  "src/suites/data_engineer/src/modules/provider-dbt",
  "src/suites/data_engineer/src/modules/provider-catalog",
]
