[workspace]
resolver = "2"
members = [
  "src/runtime",
  "src/core",
  "src/http-protocol",
  "src/transport",
  "src/view",
  "src/suites/data_engineer",
  "src/suites/kb",
  "src/suites/goggles_review",
  "src/suites/suite_debugger",
  "src/modules/adaptors/storage-s3",
  "src/modules/adaptors/storage-local",
  "src/modules/adaptors/storage-memory",
  "src/modules/providers/vector-lance",
  "src/suites/data_engineer/src/modules/provider-postgres",
  "src/suites/data_engineer/src/modules/provider-bigquery",
  "src/suites/data_engineer/src/modules/provider-athena",
  "src/suites/data_engineer/src/modules/provider-dbt",
  "src/suites/data_engineer/src/modules/provider-catalog",
  "src/suites/data_engineer/src/modules/provider-snowflake",
  "src/suites/data_engineer/src/modules/provider-mssql",
  "src/suites/data_engineer/src/modules/provider-skippr",
  "src/suites/data_engineer/src/modules/provider-databricks",
  "src/suites/data_engineer/src/modules/provider-synapse",
  "src/suites/data_engineer/src/modules/provider-redshift",
  "src/suites/data_engineer/src/modules/provider-clickhouse",
  "src/suites/data_engineer/src/modules/provider-motherduck",
  "src/bins/skippr",
  "src/bins/skippr-admin",
]
