[package]
name = "react-module-storage-memory"
version = "1.2.1"
edition = "2021"
description = "Private Skippr React crate: react-module-storage-memory"
license = "Apache-2.0"
publish = ["react-cargo"]

[dependencies]
async-trait = "0.1.77"
serde_json = "1.0.85"
react-core = { path = "../../../core", version = "1.2.1", registry = "react-cargo" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
