[package]
name = "react-suite-goggles-review"
version = "1.2.3"
edition = "2021"
description = "Private Skippr React crate: react-suite-goggles-review"
license = "Apache-2.0"
publish = ["react-cargo"]

[dependencies]
async-trait = "0.1.77"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4", "serde"] }
chrono = "0.4"
reqwest = { version = "0.12", features = ["json"] }

react-core = { path = "../../core", version = "1.2.3", registry = "react-cargo" }
